POST http://localhost:5079/api/deadlinetask
Content-Type: application/json

{
    "name": "mas",
    "description": "I want to make POST request",
    "statusUpdatedDate": "1900-11-08T08:00:00",
    "deadline": "1900-11-08T08:00:00",
    "status":"active",
    "priority":0

} 