POST http://localhost:5079/api/task/getAll
Content-Type: application/json

{
    "filter": null,
    "orderByField": "priority",
    "orderDescending": false,
    "skip": 0,
    "take": 10,
    "taskType": "task"
}
